---
Servers:
    hosts:
        rootserver:
            ansible_host: borchers.ninja
            ansible_user: root
            hostvars:
                snmp_location: "NetCup"
                ntp_enabled: True
                ntp_manage_config: True
                ansible_python_interpreter: /usr/bin/python3
            groups: [remote_servers]
        new_server:
            ansible_host: archangel-media.dev
            ansible_user: root
            hostvars:
                snmp_location: "NetCup"
                ntp_enabled: True
                ntp_manage_config: True
                ansible_python_interpreter: /usr/bin/python3
            groups: [remote_servers]
        service_pi:
          ansible_host: 192.168.1.24
          ansible_user: pi
          groups: [local_stuff]
          hostvars:
            snmp_location: "Wird sich schon wiederfinden."
            ntp_enabled: True
            ntp_manage_config: True
        raspberry_pi_4:
          ansible_host: 192.168.1.23
          ansible_user: pi
          groups: [local_stuff]
          hostvars:
            snmp_location: "Steht im Wohnzimmer"
            ntp_enabled: True
            ntp_manage_config: True
        old_pi:
          ansible_host: tba
          ansible_user: pi
          groups: [local_stuff]
          hostvars:
            snmp_location: "In irgendeinem Karton (verpackt noch vom Umzug)"
            ntp_enabled: True
            ntp_manage_config: True